### ISSUE TITLE
Recommended way to integrate with Devise?

### ISSUE THREAD

**Issue by chrismanderson** [doorkeeper-gem/doorkeeper#690] opened 2015-07-12 16:50 UTC
Hello! Found this stellar gem and am working on integrating it into a Rails app with existing Devise authentication. (It's a very standard Devise setup). I was curious as to the current recommended best practices on integration. My app has both standard web views with devise authentication as well as a JSON API. I'm also just using the `password` grant type.

I've seen a couple issues in this repo (such as https://github.com/doorkeeper-gem/doorkeeper/issues/504) and looked at some of the demo apps as well but couldn't quite find the answers I was looking for. I'd like to know the recommended methods of setting up `doorkeeper.rb` and some of the app controller methods. My main questions/requirements are as follows:

1. How should I manage the Devise `authenticate_user!` and the Doorkeeper `doorkeeper_authorize!` methods? Ideally, I'd have `authenticate_user!` in my main `ApplicationController` file, and `doorkeeper_authorize!` in my base API controller. Should I skip `authenticate_user!` in my API controllers? Or, is there a way to just use `authenticate_user!` in a way that will either get a Devise user from a cookies for HTML requests or from a token for JSON requests.

2. What's the best way of getting access to the Devise `current_user` in my API controllers? Is there a way to setup my Doorkeeper config to automatically to populate `current_user` in my API controllers? Or, should I override `current_user` in my base API controller, and do something like 

         def current_user
           @current_user ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
         end

I'm happy to add any information to the wiki or create a demo app as well. Thanks so much in advance!

**Comment by tute** [comment] 2015-07-13 10:39
I'm right now out of the office, but recently @maclover7 was working on very similar code. Probably he can help you!

Also, in general, anything you consider useful documentation should be added to the wiki, and if it's general documentation a PR to the README is best.

Thanks!

**Comment by maclover7** [comment] 2015-07-14 17:45
Hi @chrismanderson,

1. For the before authenticate_user!, you should just add skip_ in your base API controller and it should work fine.

2. That looks good what you have for your current_user finding method.

Post here if you encounter any other problems or have any other questions.

**Comment by tute** [comment] 2015-07-15 07:33
Thank you, @maclover7! @chrismanderson does that help you? Do you think we can improve documentation or the wiki, that would easy your onboarding?

**Comment by tute** [comment] 2015-07-27 10:51
@chrismanderson please let me know if we can improve docs in your opinion. Closing this issue for now, as it's not a bug in doorkeeeper. Thanks for your input!

**Closed by tute** 2015-07-27 10:51 UTC
