### ISSUE TITLE
Some Flows Redirect URI issues

### ISSUE THREAD

**Issue by dhbahr** [doorkeeper-gem/doorkeeper#631] opened 2015-04-14 13:35 UTC
First of all I'll say that my client application is not written on ruby, hence does not use Doorkeeper internally. I'm processing Doorkeeper responses manually. That being said:

For some reason (Authorization Code and Resource Owner Password Credentials both work fine on this) the Implicit Grant flow callback to the Redirect URI sends parameters with a '#' rather than a '?', that is: 
http://www.example.com/oauth_cb#access_token=c2a3...
rather than
http://www.example.com/oauth_cb?access_token=c2a3...

Is this the expected behavior?

By the way: I'm using 2.1.3, would update to 2.1.4 fix that for me?

Best regards

**Comment by tute** [comment] 2015-04-18 23:10
I've never seen this. This shouldn't be related with your clients, unless they inform the incorrect URL to the provider (doorkeeper). How can I replicate this issue? Can you provide a failing test?
Thank you!

**Comment by dhbahr** [comment] 2015-04-20 14:33
Well I was testing Odoo's oauth authentication with a Ruby on Rails + doorkeeper as provider.

**Comment by tute** [comment] 2015-04-20 19:44
Can you put an application in GitHub where I can replicate the issue?

**Comment by tute** [comment] 2015-04-20 19:44
Please see http://yourbugreportneedsmore.info/

**Comment by tute** [comment] 2015-04-24 16:58
Closing as this doesn't seem like an issue in doorkeeper; if it is, please feel free to reopen with reproducing steps so I can work on it.

**Closed by tute** 2015-04-24 16:58 UTC

**Comment by dan-corneanu** [comment] 2015-04-24 20:40
The # part of the URI is called fragment identifier.
The OAuth 2.0 specification, clearly states that for the *Implicit Grant* flow, the access token should be encoded in the fragment identifier of the redirect URI. Please see section *4.2.2.  Access Token Response* at http://www.rfc-base.org/txt/rfc-6749.txt

As far as I can tell, this is expected behavior and conforms to the specification.

The reason for using the fragment identifier is somehow security related. The fragment identifier doe not get passed by the user agent to the server (never) and so the chances of it getting logged somewhere and licking to a 3rd party are mitigated.

Ex. query parameters (that appear in your browser's location bar) are sent in the Referer [sic] HTTP header when the user agent makes a request for a resource imbedded in your page (like an image, font etc.) Thus they can be logged by proxies or other server side component.

Hope this helps.

**Comment by dhbahr** [comment] 2015-04-25 21:59
Thanks for your insight, I really missed that from the rfc6749.

Best regards
