### ISSUE TITLE
Doorkeeper initialization autoload - warning

### ISSUE THREAD

**Issue by jasonjho** [doorkeeper-gem/doorkeeper#1275] opened 2019-06-18 19:13 UTC
After upgrading to Rails 6.0.0.rc1, the doorkeeper initializer triggers a warning on server start with the following:

```DEPRECATION WARNING: Initialization autoloaded the constant RedirectUriValidator.```

I believe this has to do w/ the new zeitwerks loader and moving away from autoloading behavior from within initializers.

Has anyone run into this? Not sure how to fix this since this seems to be happening with Doorkeeper itself.

**Comment by nbulaj** [comment] 2019-06-26 13:23
Hi @jasonjho . Thanks for reporting this!

@jasl I remember you did some refactoring in order to add support for Rails 6, could you please take a look at this?

**Comment by jasl** [comment] 2019-06-26 13:28
@nbulaj I'll check this later

**Comment by jasl** [comment] 2019-06-26 14:54
@nbulaj @jasonjho 

I pulled the master and `bundle update`, there's no warning on `rails s` and `rails spec`.

@jasonjho which version of doorkeeper you in use? could you try latest master branch? could you diff your doorkeeper initializer with the latest?

Thank you!

**Comment by nbulaj** [comment] 2019-07-04 12:42
Hi @jasonjho ! Any updates here?

**Comment by jasonjho** [comment] 2019-07-04 13:54
Hi @nbulaj @jasl  I tested this using doorkeeper 5.2.0.rc2 and rails6.0.0.rc1 and I'm still seeing the following warning: 

```
DEPRECATION WARNING: Initialization autoloaded the constant RedirectUriValidator.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload RedirectUriValidator, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.
```

Running `rails s` doesn't actually show an error on startup. I only see this deprecation warning show up in the development logs.  @nbulaj do you see any of this in your dev or production logs on initialization? I'm pretty sure it's from the doorkeeper init file -- since removing will cause the warning to go away.

**Comment by nbulaj** [comment] 2019-07-04 14:05
Actually I think it related not to initializer itself, but to Rails autoloading. Seems like it autoloads all the files under `app/` directory and now it is deprecated. And we have such file - it's `RedirectUriValidator`. Need to check how to load such files now with Zeitwerk

**Comment by nbulaj** [comment] 2019-07-04 14:07
We are not alone with such issue :)

https://github.com/TrestleAdmin/trestle/issues/211

**Comment by jasonjho** [comment] 2019-07-04 14:20
@nbulaj Yep! We've actually seen this quite a bit with other dependencies. Definitely a side effect with the new zeitwerk loading mechanism. 

In the meantime, the short term (or maybe even long?) fix is to simply `require 'redirect_uri_validator'` at the top of the initializer.

**Comment by jasl** [comment] 2019-07-09 06:57
OK, so I need to create a new project to take a look.

It is strange that I have a Rails 6.0.0.rc1 project with Doorkeeper and I'm not find this issue, or maybe I'm not notice that.

**Comment by nbulaj** [comment] 2019-08-01 11:27
Any chances to fix it for 5.2 release :pray: ? I can't reproduce myself :(

**Comment by jasl** [comment] 2019-08-01 11:29
@nbulaj 
I'll try this tonight, will reply if I can or I can not reproduce it

**Comment by jasl** [comment] 2019-08-01 18:17
@nbulaj 

```
Using doorkeeper 5.2.0.rc2 from https://github.com/doorkeeper-gem/doorkeeper.git (at master@5277f4a)
Using doorkeeper-i18n 5.0.2
Using doorkeeper-openid_connect 1.6.1
Using rails 6.0.0.rc2
Using zeitwerk 2.1.9
Using bundler 2.0.2
```

I still can't reproduce the warning.

**Comment by nbulaj** [comment] 2019-08-01 18:36
@jasl maybe try to enable admin panel and try to create an application. Seems like deprecation connected to redirect uri validator, so we need to call it. Maybe enable eager loading I don't know...

**Comment by jasl** [comment] 2019-08-01 18:51
@nbulaj 

Still can't reproduce, I don't think putting `RedirectUriValidator` in `app/validators` breaks the rule of Zeitwerk, and in `rails console` type `RedirectUriValidator` can get the class correctly, so I don't know how to trigger this.

But, I think there's a simple & stupid way to prevent the issue, we can just move the validator from `app/validators` to `lib/doorkeeper/validators`, and `require` it manually in `lib/doorkeeper.rb`

**Comment by nbulaj** [comment] 2019-08-01 18:58
It will be good, but only for _active_record_ orm (not sequel, mongoid or any other)

**Comment by jasl** [comment] 2019-08-01 19:30
@nbulaj PR attached

**Comment by nbulaj** [comment] 2019-08-02 07:06
Thanks @jasl for your work! I think we can close this issue, but @jasonjho feel free to ping me if it didn't solve

**Closed by nbulaj** 2019-08-02 07:06 UTC
Labels: enhancement

**Comment by ahaverty** [comment] 2019-12-06 09:13
@nbulaj I think my issue is related to this based on your comment. @jasl I have repro steps [here](https://github.com/doorkeeper-gem/doorkeeper/issues/1328) with the v5.2.2 release.

**Comment by jasl** [comment] 2019-12-06 12:56
BTW, In Rails 6, we no longer need any kinds of `require_dependency`, and a reference change are <https://github.com/rails/rails/commit/1d2a2d9143556460cd44e17ab3553091a182cd0b>

**Comment by fxn** [comment] 2021-11-11 13:16
I was facing this in a project using 4.4.3. Let me shed some light.

This change in Rails is unrelated to Zetiwerk, really. It is a logical change that should have happened if the autoloader did not change.

Initialization does not reboot the application (that is the point). Therefore, if you autoload a _reloadable_ class or module during initialization, on reload, changes won't have any effect on the spot you used them before. Whatever you used the previous version for is stale. For example, you included a module in an ancestor chain, or well, you used the value returned by the constant for _something_.

That does not make sense, and people wondered why changes don't have effect. It should never have been allowed.

So, Rails is warning about this gotcha in Rails 6.x, and in Rails 7 you just cannot autoload _reloadable_ code during initialization. You can still autoload code from the `autoload_once_paths`, since those are not reloadable.

**Comment by nbulaj** [comment] 2021-12-03 19:26
Thanks @fxn ! 

Maybe you as an expert in autoloading and Rails app loading could advise what should be checked for https://github.com/doorkeeper-gem/doorkeeper/issues/1513 ? :pray:
