### ISSUE TITLE
Proposal: move MongoDB support back into main repo

### ISSUE THREAD

**Issue by johnnyshields** [doorkeeper-gem/doorkeeper#800] opened 2016-03-11 11:24 UTC
In Doorkeeper 3.x MongoDB support was moved into `doorkeeper-mongodb` gem. While this is well-intentioned and gives the appearance of "cleanliness", in reality it will cause MongoDB to constantly break since Mongo ORM classes are using mixins from the main repo, and Mongo specs are no longer covered by Travis CI.

As Doorkeeper 4.x dropping lots of legacy support, I think it would be reasonable that DK 4.x supports only Mongoid 5, and drops support for MongoMapper which no one uses. This way there would only be one extra set of ORM classes (Mongoid 5.)

Would you accept a PR that re-adds Mongo into this repo?

**Comment by johnnyshields** [comment] 2016-03-11 12:13
If we do really want separate repos, we should divide the main repo specs into `/unit/` and `/integration/` folders so we can copy only the `/integration/` ones by hand into the `doorkeeper-mongodb` gem everytime the `doorkeeper` gem's version increases, and according bump the `doorkeeper-mongodb` gem version. This is obviously not fun.

**Comment by tute** [comment] 2016-03-11 15:42
Hi @johnnyshields. Thanks for your feedback.

> In Doorkeeper 3.x MongoDB support was moved into doorkeeper-mongodb gem. While this is well-intentioned and gives the appearance of "cleanliness", in reality it will cause MongoDB to constantly break since Mongo ORM classes are using mixins from the main repo, and Mongo specs are no longer covered by Travis CI.
>
> Would you accept a PR that re-adds Mongo into this repo?

I would not accept such a PR. The issue is that I'm the sole doorkeeper maintainer for now, and I don't use those ORMs. I can't thus guarantee that the ORM extensions work properly, wherever we put the code.

> If we do really want separate repos, we should divide the main repo specs into `/unit/` and `/integration/` folders so we can copy only the `/integration/` specs by hand into the `doorkeeper-mongodb` gem everytime the `doorkeeper` gem's version increases, and according bump the `doorkeeper-mongodb` gem version. This is obviously not fun.

`doorkeeper-mongodb` fetches on each test run `doorkeeper` (main) specs, and runs its test suite with the ORM extensino plugged in. See how this happens in https://github.com/doorkeeper-gem/doorkeeper-mongodb/blob/master/Rakefile#L4.

If they get out of sync, we can declare what versions of `doorkeeper` that are known to work well in `doorkeeper-mongodb`, making bundler configure both libraries properly. Also, we'll need to make the `Rakefile` smart about running specs for the appropriate `doorkeeper` version.

> As Doorkeeper 4.x dropping lots of legacy support, I think it would be reasonable that DK 4.x supports only Mongoid 5, and drops support for MongoMapper which no one uses. This way there would only be one extra set of ORM classes (Mongoid 5.)

We should definetly remove support for previous mongoid versions if they were EOL'd. Otherwise, we should evealuate how hard it is to keep supporting them, and try to measure how many people are using them before dropping support.

---

I am looking for maintainers for https://github.com/doorkeeper-gem/doorkeeper-mongodb. After we work through a few PRs together on it and if you are interested, I'll grant you access.

Thanks again for your feedback.

**Comment by johnnyshields** [comment] 2016-03-11 16:14
> The issue is that I'm the sole doorkeeper maintainer for now, and I don't use those ORMs. I can't thus guarantee that the ORM extensions work properly

I don't think this is a good reason. The specs will guarantee that the Mongoid classes are not broken. I'd be glad to help with Mongoid, but ultimately it should be low effort given A) the strong similarity between Mongoid and ActiveRecord (both use ActiveModel as base) and B) the low frequency of schema DB changes in this relatively mature repo.

> doorkeeper-mongodb fetches on each test run doorkeeper (main) specs

I missed the Rakefile on the mongodb gem when I read the through code. IMHO this is difficult to work with, compared to the cost of keeping Mongoid ORM within the main repo.

> I am looking for maintainers

I'll give it a thought and I may raise a PR for mongodb. Today I upgraded DK 1.0.0 to 2.2 as it looks like there's some issues on the 3.x branch with Mongo, but ran out of time today.

**Comment by johnnyshields** [comment] 2016-03-11 16:18
Just one more thought here. If Mongoid classes we're 80% unique and 20% shared with the main repo, I'd be in favor of having them in a gem. But as it stands 80%+ of their functionality comes from the mixins living in the main repo, and the split feels very unnatural.

**Comment by tute** [comment] 2016-03-11 17:47
> > The issue is that I'm the sole doorkeeper maintainer for now, and I don't use those ORMs. I can't thus guarantee that the ORM extensions work properly
>
> I don't think this is such a good reason :). The specs will guarantee that the Mongoid classes are not broken. I'd be glad to help with Mongoid, but ultimately it should be low effort given A) the strong similarity between Mongoid and ActiveRecord (both use ActiveModel as base) and B) the low frequency of schema DB changes in this relatively mature repo.

On principle I agree on everything you say. But in practice, not using mongo adapters in my projects have led to bugs being released into the official gem releases. Reports would come in from people who wouldn't expect breakages on non-major releases, and I would not have the tools or time to fix it myself.

Also, I don't agree with abstracting out data stores as ActiveRecord proposes. I think different databases have different weaknesses and strengths, and I want to maximize the use of the tools I have rather than using the lowest common denominator. It's not just the database schema that differs.

In https://robots.thoughtbot.com/splitting-an-open-source-project-in-two-with-git-submodules I state other problems that were addressed by separating the repositories. (While reviewing it, I see that `doorkeeper-mongodb` has the proper `doorkeeper` version already specified in the git submodule, and thus test suite is reliably green.)

> > doorkeeper-mongodb fetches on each test run doorkeeper (main) specs
>
> I missed the Rakefile on the mongodb gem when I read the through code. IMHO this is difficult to work with, compared to the cost of keeping Mongoid ORM within the main repo.

Agree that this tests setup are more complex. More on why we chose this tradeoff is on the blog post. I should probably link to it from the project's README.

> > I am looking for maintainers
>
> I'll give it a thought and I may raise a PR for mongodb. Today I upgraded DK 1.0.0 to 2.2 as it looks like there's some issues on the 3.x branch with Mongo, but ran out of time today.


Sounds good, let me know how it goes.

> Just one more thought here. If Mongoid classes we're 80% unique and 20% shared with the main repo, I'd be in favor of having them in a gem. But as it stands 80%+ of their functionality comes from the mixins living in the main repo, and the split feels very unnatural.

Again, this has been said elsewhere, but if we add mongoid to the repo, mongomapper comes as well. And then sequel? And what about others? Where's the line? How many ORMs should doorkeeper (myself, for now), maintain? Better to be consistent, and provide a canonical example of how to extend doorkeeper.

---

Again, thanks for your input.

**Comment by tute** [comment] 2016-04-19 03:54
Will leave doorkeeper as is for the foreseeable future. Closing this issue for now, happy to continue further discussion.

**Closed by tute** 2016-04-19 03:54 UTC
