### ISSUE TITLE
Check for valid client_id and secret before creating access token in assertion grant flow

### ISSUE THREAD

**Issue by StarWar** [doorkeeper-gem/doorkeeper#699] opened 2015-07-26 10:55 UTC
Currently I'm using following code to generate access_token from assertion using assertion grant flow

``` ruby
resource_owner_from_assertion do
    User.from_fb_access_token(params[:assertion]) if params[:assertion]
end
```

And this creates access_token without providing client_id and client_secret. I want to allow only valid applications to do so. With current solution anybody can access a new token with any fb access token.

When I check in rails console it gives following output
``` ruby
Doorkeeper::AccessToken.last
  Doorkeeper::AccessToken Load (3.7ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens"  ORDER BY "oauth_access_tokens"."id" DESC LIMIT 1
  Doorkeeper::AccessToken Load (3.7ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens"  ORDER BY "oauth_access_tokens"."id" DESC LIMIT 1
 => #<Doorkeeper::AccessToken id: 33, resource_owner_id: 4, application_id: nil, token: "59b64087ebca1e32a6e5c898ed60d575cc22843b622de9a836...", refresh_token: "2008a728fa938888cf31ffbd7f8e45ad125d784fd934b9280f...", expires_in: 120, revoked_at: "2015-07-26 09:21:52", created_at: "2015-07-26 09:20:08", scopes: "public">
```

As you can see `application_id` is `nil`. 

Thanks!

**Comment by StarWar** [comment] 2015-07-27 03:48
Since application Id is nil, refresh token also works without passing client_id and client_secret in this case.

I'm using following my android and it works.

``` shell
curl -F grant_type=refresh_token \
-F refresh_token=796de417cf5b57b2f59ec567a8de15a6087618684b453308518a39268b440310 \
> -X POST http://localhost:3000/oauth/token
{"access_token":"7e3eace6549cbd95a57525e40754a345e40022a23e5641574451a248f8e40945","token_type":"bearer","expires_in":120,"refresh_token":"1227c6f1f791d4ed0b9014a9c3f9136d7bddd077ae4cbe7c16fc40768f18d21t","scope":"public","created_at":1437968777}
```

**Comment by tute** [comment] 2015-07-27 04:52
Should this issue belong to https://github.com/doorkeeper-gem/doorkeeper-grants_assertion? Also, note that that repository is in need of maintainer.

**Comment by tute** [comment] 2015-07-27 04:54
We have an issue there, closing as duplicate of that one: https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/issues/11

**Closed** 2015-07-27 04:54 UTC
