### ISSUE TITLE
Access current scope from controller?

### ISSUE THREAD

**Issue by theycallmeswift** [doorkeeper-gem/doorkeeper#818] opened 2016-04-19 17:44 UTC
We have an application that may require users to fill out different profile information based on the scopes that an application needs.  For example, an application might request a `gender` scope and we would prompt the user to enter it before authorizing if the info wasn't already present.  

Is there an easy way to access the current list of request scopes from the controller?  Right now we're looking at the `@pre_auth` instance variable to figure out the scopes, but this feels hacky.

```ruby
def is_scope_defined?(scope)
  @pre_auth.scopes.to_a.include?(scope.to_s) rescue false
end
```

**Comment by tute** [comment] 2016-08-31 03:10
@theycallmeswift: does `doorkeeper_token.scopes` work for your case? Thanks!

**Comment by theycallmeswift** [comment] 2016-08-31 09:57
@tute when does `doorkeeper_token` get set for the controller? After `doorkeeper_authorize!`?

**Comment by tute** [comment] 2016-09-01 15:58
> @tute when does `doorkeeper_token` get set for the controller? After `doorkeeper_authorize!`?

Yes, it does. [`doorkeeper_token`](https://github.com/doorkeeper-gem/doorkeeper/blob/c846335ad75f2f9c7108e577cb84eaf8ab66b86f/lib/doorkeeper/helpers/controller.rb#L28-L30) is initialized and cached when its called, if `Token.authenticate` validates scopes and others.

If you need access to which scopes are required by an application, `@pre_auth` and its `client.application` are the way to go.

---

I'm not sure I understand your use case. Is it that the provider (doorkeeper) holds all the information for a user? If so, why? Should it only be concerned with tokens and user ids?

Or, is it that the clients hold the user information they need? If so, can they request authorization only when its user profiles are complete?

Thanks!

**Comment by tute** [comment] 2016-09-01 15:59
I'll close this issue, as it's not a bug in doorkeeper as far as I understand, but I'm happy to continue further discussion of your app. If we find we can improve something on doorkeeper, we'll do through a PR. Thanks!

**Closed by tute** 2016-09-01 15:59 UTC
Labels: question/discussion
