### ISSUE TITLE
redirect_uri is not properly decoded when requesting token

### ISSUE THREAD

**Issue by ragulka** [doorkeeper-gem/doorkeeper#1013] opened 2018-01-04 09:46 UTC
I'm trying to implement the Authorization Code Grant, and am getting stuck in the last step, where I want to exchange the authorization code for an access token. I've tracked the issue down to the fact that the redirect_uri is not being url-decoded before being compared to the `grant.redirect_uri` [here](https://github.com/doorkeeper-gem/doorkeeper/blob/414fad1cb92bcd904288c3223d92930b3f2ab82f/lib/doorkeeper/oauth/authorization_code_request.rb#L47).

AFAIK, the params for the POST request to `oauth/token` should be urlencoded and the Content-Type header should be `application/x-www-form-urlencoded`. Because my redirect_uri contains query params, it must be urlencoded, as otherwise the params in the redirect uri are stripped and considered as regular POST params (not part of the uri).

However, when logging the `redirect_uri` on the line I pointed to above, I can see that it's still fully url-encoded, ie something like: `http%3a%2f%2fmysite.com%3fauth%3dcallback`. Note that the same error does not occur in the initial redirect to `oauth/authorize` - the redirect_uri is still encoded in the query params, but somehow it's decoded when comparing it to the client redirect_uri. 

I may not understand the OAuth spec properly, and perhaps there is some Rails magic going on in the authorization redirect, but this seems broken to me. Perhaps I am doing something wrong?

FWIW, when I tried manually "encoding" just the equal sign `=`, ie used an url like `http://mysite.com?auth%3callback`, it worked 😕

**Comment by nbulaj** [comment] 2018-02-04 17:14
Hi @ragulka . Can you please provide me a small app example with this issue ? Is the problem exist in process of validation or in some other case? Sorry, don't have enough time to research on this :(

**Comment by ragulka** [comment] 2018-02-05 16:55
@nbulaj I'm simply getting this response to the `POST /oauth/token` request:

```json
{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

I don't have time to put together a sample app, but if you send a request to `/oauth/token` with `redirect_uri=http%3a%2f%2fmysite.com%3fauth%3dcallback`, you'll get the same response.

My knowledge of RoR is rather shallow, but it looks like the comparison is done [here](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/authorization_code_request.rb#L47-L50), but the `redirect_uri` will still be url-encoded there, which means the comparison will inevitably fail.

**Comment by nbulaj** [comment] 2018-02-08 12:55
Can you please provide exact redirect URI that you used? With something like "_https://mysite.com/?auth=callback_" I have a  "`The redirect uri included is not valid`." error

There is [something strange in Doorkeeper specs](https://github.com/doorkeeper-gem/doorkeeper/blob/master/spec/validators/redirect_uri_validator_spec.rb#L42):

```ruby
it 'is invalid when the uri has a query parameter' do
    subject.redirect_uri = 'https://example.com/abcd?xyz=123'
    expect(subject).to be_valid
end
```

O_o

**Comment by f3ndot** [comment] 2018-02-10 17:49
Looks like the history of that funny spec is that Doorkeeper originally disallowed query params in the callback, but was enhanced to support preserving original ones while adding its own:

https://github.com/doorkeeper-gem/doorkeeper/commit/82e7f70519ceab688000953a5d7c908abf59f68c

Will update spec name to match intent.

**Comment by nbulaj** [comment] 2018-02-20 14:52
Hi @ragulka . How can I reproduce your issue ? I've tried to send encoded params, but have no bugs

**Comment by nbulaj** [comment] 2018-03-11 12:03
Hi @ragulka . Can you provide the steps to reproduce the issue?

**Comment by nbulaj** [comment] 2018-03-28 14:33
Currently I'm closing this issue because of no ability to reproduce. It somebody or @ragulka will face this problem - feel free to send some instructions on how to check it and some PR . Thanks!

**Closed by nbulaj** 2018-03-28 14:33 UTC
Labels: bug?
