### ISSUE TITLE
resource owner credentials grant possible without client credentials

### ISSUE THREAD

**Issue by bpieck** [doorkeeper-gem/doorkeeper#645] opened 2015-04-26 23:23 UTC
Oauth specifications sais, that resource owner credentials grant flow always has to ensure, client credentials are correct. Although doorkeeper checks credentials, if authorization header is set - when I don't set an authorization header, I can get an access token.

**Comment by tute** [comment] 2015-04-26 23:28
Duplicate of: https://github.com/doorkeeper-gem/doorkeeper/issues/543. If after reading that discussion you think it's still an issue, we can reopen that issue. Thanks for your input!

**Comment by bpieck** [comment] 2015-04-26 23:40
I tried to understand, how these are similar - but failed. Still: I can get an access_token only with username and password - but without client credentials (not from basic auth and not from params). So I think, it still is an issue that does not fit to oauth specifications. But if you already thought it through, I won't bother you with this.
Thanks for your fast reply anyway.

**Comment by bpieck** [comment] 2015-04-27 05:48
Hm, I just checked: I can do a refresh token request as well without any client verification! I just deleted the Authentication header there, too. I did not add any parameters.
curl -i -X POST -H "content-type=[application/x-www-form-urlencoded]" -H "Accept=[*/*]" -d 'grant_type=refresh_token&refresh_token=902837df8e907686fc156ceebf461360df9d334e0dcb848b650dc605037853bb' https://oauth.myoauthdomain.com/oauth/token

I got a new token. I am really sure, this should not be, and this is not expected by developers, who are using this great gem.
When I set the authentication header, client credentials are validated correctly. But when I did not set any information, I just came through without validation.

**Comment by bpieck** [comment] 2015-04-27 11:01
I just monkey patched Doorkeeper::Oauth::PasswordAccessTokenRequest and Doorkeeper::Oauth::RefreshTokenRequest
from:

      def validate_client
        !client_credentials || !!client
      end

to:

      def validate_client
        !!client
      end

Since oauth specifications disallow at least for RefreshToken requests not to use the client_credentials (https://tools.ietf.org/html/rfc6749#section-1.5), would you be interested in some pull request for making these both configurable? resource owner credentials grant describes client credentials to be mandatory for confidential client types, too (https://tools.ietf.org/html/rfc6749#section-4.3.2). Then I would write something rspec tested until the end of this day.

**Comment by tute** [comment] 2015-04-28 13:03
Let me revisit this issue, will get back to you next week! Thanks for your input.

**Comment by tute** [comment] 2015-05-01 18:38
From the spec, section 1.5:

> The client authentication requirements are based on the client type and on the authorization server policies.

Are you sure "oauth specifications disallow at least for RefreshToken requests not to use the client_credentials"?

From section 4.3.2:

> If the client type is confidential or the client was issued client credentials (or assigned other authentication requirements), the client MUST authenticate with the authorization server as described in Section 3.2.1.

So it depends on the client. How would doorkeeper enforce it?

**Comment by bpieck** [comment] 2015-05-04 17:15
Sorry for wasting your time. It seems I haven't correctly read this (or read to many articles not directly from oauth, like this one: https://developers.google.com/identity/protocols/OAuth2WebServer#refresh) - my fault. So you are right, that both are only mandatory for confidential clients. Since you already ensure client credentials will be checked, if given, it's all on the developers side, to ensure, data is only shown, unless doorkeeper_token.application.nil? (what could happen with resource owner credentials grant), and perhaps monkey patch some logic for confidential clients to be checked on refresh token grant.
Since I only want to allow resource owner credentials grant for internal applications, I will still go with my solution, that already needed some other modifications :) - but that of course is not oauth conform, so not needed to be discussed here ^^. Sorry again.

**Comment by tute** [comment] 2015-05-04 20:01
Closing the issue then, thanks for sharing!

**Closed by tute** 2015-05-04 20:01 UTC

**Comment by joshuairl** [comment] 2015-10-21 15:34
I'm sorry for posting this here but not sure where else to post it...
I'm having a problem that seems to be isolated to ajax requests executed within the context of a cordova app... I send a /oauth/token.json POST grant_type='password' with credentials and it returns an access token properly.

Then I logout, calling a revoke on that same token.

Then I login with different username / password and it's returning an access_token for the previous user even though I have confirmed the request is passing username / password properly of the second user the /oauth/token.json is assuming the old user id... guessing it's getting it from a session but cannot figure out for the life of me how it is using the user_id of the previous user... .and why it would even think to use the user_id of the previous user on an /oauth/token.json POST with grant_type='password'

Also, I'm using Devise too.

**Comment by bpieck** [comment] 2015-10-26 07:52
When you are doing the api call for resource_owner_credentials_grant, there is no session involved on doorkeeper side. That would be in the other grants, where you are redirected to doorkeeper app, login, and redirect back. I think the caching of data must happen on that side of the request.

I myself have overwritten Doorkeeper::TokensController create action and added some logs (not password itself - but at least the username and user_id, so I can check what I clients send me, and which user_id Doorkeeper found there.

When you are able to run your doorkeeper application locally or in some development container, where you can user a debugger, I would set a debugger inside resource_owner_from_credentials in doorkeeper initializer. Just check, which data you get there. When client sent twice the same data, you can be pretty sure, the problem is on the client, not on the doorkeeper application.
