### ISSUE TITLE
Can't mass-assign protected attributes

### ISSUE THREAD

**Issue by cdussud** [doorkeeper-gem/doorkeeper#878] opened 2016-08-25 19:32 UTC
I've recently upgraded an app from Doorkeeper 1.4.2 to 4.2. I'm now getting this warning

WARNING: Can't mass-assign protected attributes for Doorkeeper::AccessGrant: application_id, resource_owner_id, expires_in, redirect_uri, scopes

and then get a ActiveRecord::RecordInvalid exception when the access grant attempts to save.

This is on Rails 4.2.

**Comment by tute** [comment] 2016-08-25 20:23
Can you post the full stack trace please?

**Comment by cdussud** [comment] 2016-08-26 20:10
The relevant callstack is this:

vendor/bundle/ruby/2.1.0/gems/doorkeeper-4.2.0/lib/doorkeeper/oauth/authorization/code.rb:13:in `issue_token'
vendor/bundle/ruby/2.1.0/gems/doorkeeper-4.2.0/lib/doorkeeper/oauth/code_request.rb:15:in `authorize'
vendor/bundle/ruby/2.1.0/gems/doorkeeper-4.2.0/app/controllers/doorkeeper/authorizations_controller.rb:8:in `new'

**Comment by tute** [comment] 2016-08-26 21:27
I need more information to be able to replicate it. Please see http://yourbugreportneedsmore.info/. Thanks!

**Comment by cdussud** [comment] 2016-08-27 22:22
Sorry about the lack of info. The answer is fairly straightforward actually. The app I'm running was upgraded from Rails 3 to 4 and still has the protected_attributes gem.

The workaround for me is to do this
```
Doorkeeper::AccessGrant.class_eval do
  attr_accessible :application_id, :resource_owner_id, :expires_in, :redirect_uri, :scopes
end

Doorkeeper::AccessToken.class_eval do
  attr_accessible :application_id, :resource_owner_id, :scopes, :expires_in, :use_refresh_token
end
```

I'm assuming that Doorkeeper has switched to using strong parameters in its application controller and expects other apps to do so. For me the right thing to do is to get rid of protected_attributes from my project.

**Comment by tute** [comment] 2016-08-28 04:01
Great, thanks for publishing! Could you please add this information into the wiki? Thanks for asking and responding.

**Comment by daveallie** [comment] 2016-08-29 10:14
This is effectively the same issue as #877 just a different workaround (this workaround specifies a whitelist, whereas the workaround in #877 specifies a blacklist). Either will work, but this is something that Doorkeeper should be including if the `protected_attributes` gem is being used.

**Comment by tute** [comment] 2016-08-29 13:55
> This is effectively the same issue as #877 just a different workaround (this workaround specifies a whitelist, whereas the workaround in #877 specifies a blacklist).

Indeed, closing as duplicate of #877.

> Either will work, but this is something that Doorkeeper should be including if the protected_attributes gem is being used.

I'd rather see it in the wiki or README as a workaround for users to take. The condition to check when we should be calling `attr_accessible` was always buggy, the workaround is simple enough, and that's a deprecated API.

**Closed by tute** 2016-08-29 13:55 UTC
Labels: more info needed

**Comment by cdussud** [comment] 2016-08-29 14:25
I'll add something to the wiki about this.

**Comment by cdussud** [comment] 2016-08-29 14:37
I added a page [here](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-protected_attributes-in-Rails-4)

I didn't add a link to it on your home page because I wasn't sure where it'd belong.

**Comment by tute** [comment] 2016-08-29 14:42
Thank you! 👏  I'll link to it.
