### ISSUE TITLE
“uninitialized constant Doorkeeper::Rails::Application” error installing the Doorkeeper gem

### ISSUE THREAD

**Issue by jdonadob** [doorkeeper-gem/doorkeeper#1332] opened 2019-11-24 12:22 UTC
### Steps to reproduce
**Step 1:** `bundle add doorkeeper`
**Step 2:** `bundle exec rails generate doorkeeper:install`

### Actual behavior
This error is shown:
![image](https://user-images.githubusercontent.com/9633174/69494486-4d194980-0e8a-11ea-9f3d-348f5795c870.png)

**Ruby version**: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]`

**Gemfile.lock**:

<details>

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.3)
      actionpack (= 5.2.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.3)
      actionview (= 5.2.3)
      activesupport (= 5.2.3)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.3)
      activesupport (= 5.2.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.3)
      activesupport (= 5.2.3)
      globalid (>= 0.3.6)
    activemodel (5.2.3)
      activesupport (= 5.2.3)
    activerecord (5.2.3)
      activemodel (= 5.2.3)
      activesupport (= 5.2.3)
      arel (>= 9.0)
    activestorage (5.2.3)
      actionpack (= 5.2.3)
      activerecord (= 5.2.3)
      marcel (~> 0.3.1)
    activesupport (5.2.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (9.0.0)
    bcrypt (3.1.13)
    bcrypt (3.1.13-java)
    bootsnap (1.4.5)
      msgpack (~> 1.0)
    bootsnap (1.4.5-java)
      msgpack (~> 1.0)
    builder (3.2.3)
    byebug (11.0.1)
    concurrent-ruby (1.1.5)
    crass (1.0.5)
    doorkeeper (5.2.2)
      railties (>= 5)
    erubi (1.9.0)
    ffi (1.11.2)
    ffi (1.11.2-java)
    ffi (1.11.2-x64-mingw32)
    ffi (1.11.2-x86-mingw32)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.7.0)
      concurrent-ruby (~> 1.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.3.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mimemagic (0.3.3)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.13.0)
    msgpack (1.3.1)
    msgpack (1.3.1-java)
    msgpack (1.3.1-x64-mingw32)
    msgpack (1.3.1-x86-mingw32)
    nio4r (2.5.2)
    nio4r (2.5.2-java)
    nokogiri (1.10.5)
      mini_portile2 (~> 2.4.0)
    nokogiri (1.10.5-java)
    nokogiri (1.10.5-x64-mingw32)
      mini_portile2 (~> 2.4.0)
    nokogiri (1.10.5-x86-mingw32)
      mini_portile2 (~> 2.4.0)
    puma (3.12.1)
    puma (3.12.1-java)
    rack (2.0.7)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.3)
      actioncable (= 5.2.3)
      actionmailer (= 5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      activemodel (= 5.2.3)
      activerecord (= 5.2.3)
      activestorage (= 5.2.3)
      activesupport (= 5.2.3)
      bundler (>= 1.3.0)
      railties (= 5.2.3)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.2.3)
      actionpack (= 5.2.3)
      activesupport (= 5.2.3)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (13.0.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    ruby_dep (1.5.0)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (4.0.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.1)
    thor (0.20.3)
    thread_safe (0.3.6)
    thread_safe (0.3.6-java)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    tzinfo-data (1.2019.3)
      tzinfo (>= 1.0.0)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-driver (0.7.1-java)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)

PLATFORMS
  java
  ruby
  x64-mingw32
  x86-mingw32
  x86-mswin32

DEPENDENCIES
  bcrypt (~> 3.1.7)
  bootsnap (>= 1.1.0)
  byebug
  doorkeeper (~> 5.2)
  listen (>= 3.0.5, < 3.2)
  puma (~> 3.11)
  rails (~> 5.2.3)
  spring
  spring-watcher-listen (~> 2.0.0)
  sqlite3
  tzinfo-data

RUBY VERSION
   ruby 2.6.3p62

BUNDLED WITH
   2.0.1
```
</details>

**Comment by nbulaj** [comment] 2019-11-27 13:39
Could you please try to disable the `spring` gem and try it again?

**Comment by jdonadob** [comment] 2019-11-28 00:12
I did it and these errors are shown:

bundle exec rails generate doorkeeper:install

Traceback (most recent call last):
        24: from bin/rails:9:in `<main>'
        23: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        22: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        21: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        20: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        19: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        18: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
        17: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
        16: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
        15: from /home/johan/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        14: from /home/johan/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        13: from /home/johan/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        12: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        11: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        10: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command/actions.rb:22:in `require_application!'
         9: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         8: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
         7: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         6: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
         5: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
         4: from /home/johan/Desarrollos/sample/config/application.rb:20:in `<main>'
         3: from /home/johan/Desarrollos/sample/config/application.rb:21:in `<module:Doorkeeper>'
         2: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
         1: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant': uninitialized constant Doorkeeper::Rails::Application (NameError)
        25: from bin/rails:9:in `<main>'
        24: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        23: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        22: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        21: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        20: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        19: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
        18: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
        17: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
        16: from /home/johan/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        15: from /home/johan/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        14: from /home/johan/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        13: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        12: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        11: from /home/johan/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command/actions.rb:22:in `require_application!'
        10: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         9: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
         8: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         7: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
         6: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
         5: from /home/johan/Desarrollos/sample/config/application.rb:20:in `<main>'
         4: from /home/johan/Desarrollos/sample/config/application.rb:21:in `<module:Doorkeeper>'
         3: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
         2: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
         1: from /home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/johan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant Doorkeeper::Rails::Application (NameError)

**Comment by nbulaj** [comment] 2019-12-10 08:19
Maybe you already added Doorkeeper routes or something else? :thinking: I don't sure why it happens, here we need a sample application where we can reproduce an error to see what happening

**Comment by nbulaj** [comment] 2019-12-26 09:26
Any update here?

**Comment by jdonadob** [comment] 2019-12-26 10:32
I can't send a sample application because I can't even install doorkeeper gem to start my application.

**Comment by nbulaj** [comment] 2019-12-31 13:15
I can't do anything with it because I just can't reproduce the issue :(

**Comment by nbulaj** [comment] 2019-12-31 13:21
What do you have in this file on reported lines? :thinking: 

![image](https://user-images.githubusercontent.com/1443426/71622839-92e3d300-2be9-11ea-8fb7-35781c91ce58.png)

**Comment by jdonadob** [comment] 2020-01-01 18:11
![image](https://user-images.githubusercontent.com/9633174/71644547-1fe56580-2c98-11ea-8a71-376bc8f121ea.png)


```
require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
# require "sprockets/railtie"
require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Doorkeeper
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.2

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    # Only loads a smaller set of middleware suitable for API only apps.
    # Middleware like session, flash, cookies can be added back manually.
    # Skip views, helpers and assets when generating a new resource.
    config.api_only = true
  end
end

```

**Comment by nbulaj** [comment] 2020-01-09 12:05
Still can't reproduce with RVM, Ruby 2.5 and Rails 5.2 :disappointed:

**Comment by nbulaj** [comment] 2020-01-31 15:12
Oh my, I didn't see it first time! For sure you're creating conflicts with Doorkeeper Application model - `Doorkeeper::Application`. You should name your Rails app with another name.

Thanks @moiristo - you found it! :D

**Comment by nbulaj** [comment] 2020-01-31 15:14
I think we can now close this issue

**Closed by nbulaj** 2020-01-31 15:14 UTC
