### ISSUE TITLE
Add custom fields to access token response

### ISSUE THREAD

**Issue by domaindrivendev** [doorkeeper-gem/doorkeeper#558] opened 2015-01-19 20:28 UTC
I'm aware that OAuth 2.0 is primarily an authorization framework and is not necessarily intended for authentication. However, I'm investigating the use of the "Resource Owner Credentials" flow for managing authentication in a mobile app.

I could have the app make a second "Token Info" request  to obtain the resource owners identity (resource_owner_id) but would prefer to return this information along with the original access token response.  

I've looked at doing this through a custom TokensController that delegates to super and just appends the additional info to the response but ended up duplicating most of the code to get it to work. Can you think of a simpler way to do this that (ideally) only extends behavior as opposed to re-writing it?

Thanks for the awesome project!

**Comment by tute** [comment] 2015-01-21 22:18
@domaindrivendev I haven't thought of this before. If there's a way we can refactor internals to make it easier for you, I'd be ok merging PRs.

Closing this issue for now, as it's not a bug in doorkeeper, happy to continue discussion.

Thanks!

**Closed by tute** 2015-01-21 22:18 UTC
