### ISSUE TITLE
Bug: Able to get default scopes in the token even if they are not present in the application scopes using password grant type

### ISSUE THREAD

**Issue by kapilmittal** [doorkeeper-gem/doorkeeper#1002] opened 2017-11-27 09:40 UTC
When grant type is 'password' and application scopes are present:
     1.  when scope parameter is not present in the /oauth/token api then this api is giving token with default scopes (for exp. 'public' scope) even if 'public' scope is not present in the application scopes. 
     2. when scope parameter is present in the api and its value is 'public' then it gives following error:
         {
            "error": "invalid_scope",
            "error_description": "The requested scope is invalid, unknown, or malformed."
         }

Above 2nd point behaviour is the correct behaviour and api should behave like this for point 1 (when scope parameter is not present ) also.

Note: When grant type is client_credentials then api is working fine (It gives error when scope parameter is not present and 'public' scope is not present in the application scopes).  This issue exists for 'password' grant type.

**Comment by f3ndot** [comment] 2018-02-17 19:56
Hi @kapilmittal, I was unable to reproduce your issue with specs (see #1039). Can you put up a failing test or double check your findings?

Thanks

**Comment by nbulaj** [comment] 2018-02-17 21:41
I've double checked the specs and @f3ndot specs and could not find an error. Maybe you have a typo in your scopes or Doorkeeper initializer?

**Comment by nbulaj** [comment] 2018-03-03 14:10
Hi @kapilmittal . Any news here?

**Comment by kapilmittal** [comment] 2018-03-03 14:25
I am very sure that this issue was happening at that time. I will check this once again on Monday and let you know. Will check the specs also.

**Comment by kapilmittal** [comment] 2018-03-03 14:34
Also I remember that I looked into the doorkeeper code also and the code looked in sync with the mentioned bug because in the code, if scope parameter was not provided in the API then it was skipping the scope validation. 
Anyway, will confirm this on Monday.

**Comment by kapilmittal** [comment] 2018-03-05 10:27
Hi @f3ndot / @nbulaj 

I have verified once again and this issue still exists. 
I have checked the specs also. In the specs, 'scope' parameter is provided in the api but as mentioned in the bug, this issue exists when we don't provide the 'scope' parameter in the api (then api returns token with default scope even if that default scope is not present in the application scopes).

**Comment by kapilmittal** [comment] 2018-03-12 13:37
Hi. @f3ndot / @nbulaj . Did you have a chance to look into this again?

**Comment by nbulaj** [comment] 2018-03-15 13:50
Hi @kapilmittal . Can you please prepare the failing spec that I can use for tests and work on this issue?

**Comment by kapilmittal** [comment] 2018-03-16 06:04
Sure. will add failing spec.

**Comment by nbulaj** [comment] 2018-03-19 14:54
I've checked Client Credentials flow and I see similiar scope validation as for Password flow:

```
# Client Credentials
 def validate_scopes
    return true if @request.scopes.blank?
    #  ...
end

# Password
def validate_scopes
  return true if @original_scopes.blank?
  # ...
end
```

O_o interesting

**Comment by GeminPatel** [comment] 2018-03-19 18:11
@nbulaj for preliminary observations [I might be looking at a little older doorkeeper version but I think thats ok in this case.], below is the following conclusion that I make. 

@request.scopes:
```
      def scopes
        @scopes ||= if @original_scopes.present?
                      OAuth::Scopes.from_string(@original_scopes)
                    else
                      default_scopes
                    end
      end
```

Which means public if nothing is there. Which means that @request.scopes is not blank and therefore checked ahead.

@original_scopes on the other hand is actually blank. And so true is returned without further checks.

**Comment by nbulaj** [comment] 2018-03-20 09:10
Fixed with 54e3159 , @kapilmittal I would be very grateful if you can check the master branch for you app.

Currently default scope for Password Grant type can be set only if applications has no scopes and user/developer doesn't pass any scope string with the request.

**Comment by kapilmittal** [comment] 2018-03-20 12:16
@nbulaj I have checked your commit 54e3159. api should return default scope even if user doesn't pass any scope string with the request and applications has scopes and application scopes includes default scope.
so validate_scopes method should be like below:

```
def validate_scopes
  requested_scopes = @original_scopes
  requested_scopes  = server.default_scopes.to_s unless @original_scopes.present?
  ScopeChecker.valid?(requested_scopes, server.scopes, client.try(:scopes))
end
```

**Comment by nbulaj** [comment] 2018-03-20 12:18
@kapilmittal you mean no matter if application requires `'abc'` scope, we need to set default server scopes for the token?

**Comment by kapilmittal** [comment] 2018-03-20 13:41
yeah, there are below two options when user pass nothing:
1. try to return all default_scopes and return error if any one of them is not allowed by application.
2. return only those default scopes that are allowed by the application.

I think, 2nd option is better since it gives more flexibility in terms of defining default scopes.

**Comment by GeminPatel** [comment] 2018-04-18 15:52
@nbulaj Please consider the following case.

Doorkeeper Application has scopes in db: [read write public]

Doorkeeper default scope is: public

Api Call does not send scope parameter: 
```
curl -X POST \
  http://localhost:3000/oauth/token \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: a5fedb86-5a28-a497-0373-777f96124f57' \
  -d 'client_id=09633df7c8d3d2e1883f4a57b5662f54a9b46dac4b638555398503ebe4537326&client_secret=2d8995b954cf56f93a0b98789236a0b4f4a33e712aa56a1501dd18e7da50157a&grant_type=password&username=gemin.patel%40payu.in&password=Payu%401234'
```

Expected output: Token with public scope.

Actual output on master because of [54e31599e1d12773741483e56d6212efacc43c21]: invalid_scope
Actual output on 4.3.2: Token with public scope.

**Comment by nbulaj** [comment] 2018-04-18 16:33
Hi @kapilmittal . So you want to say that Doorkeeper 4.3.2 works as described in p. 2 of [kapilmittal comment below](https://github.com/doorkeeper-gem/doorkeeper/issues/1002#issuecomment-374601386)?

**Comment by GeminPatel** [comment] 2018-04-19 13:16
@nbulaj No 4.3.2 does not work a p. 2 of [kapilmittal comment below](https://github.com/doorkeeper-gem/doorkeeper/issues/1002#issuecomment-374601386). But it works for [geminpatel comment](https://github.com/doorkeeper-gem/doorkeeper/issues/1002#issuecomment-382436069).

Difference between both the comments is:

p. 2 of [kapilmittal comment below](https://github.com/doorkeeper-gem/doorkeeper/issues/1002#issuecomment-374601386) asks for partial scope acceptance. It wants that if no scope is passed, doorkeeper will try to give default scopes. But if the application is only permitted to get some of them and not all of them then those scopes should be given. 

[geminpatel comment](https://github.com/doorkeeper-gem/doorkeeper/issues/1002#issuecomment-382436069) asks to fix the bug introduced due to [54e315](https://github.com/doorkeeper-gem/doorkeeper/commit/54e31599e1d12773741483e56d6212efacc43c21). 

Just consider this,

Doorkeeper Application has scopes in db: [read write public]

Doorkeeper default scope is: public

What will happen if that client does not send scopes in parameters? 

In master branch it will return invalid scope.

**Comment by nbulaj** [comment] 2018-04-19 14:31
To be honest I do not understand you.

> Doorkeeper Application has scopes in db: [read write public]
> Doorkeeper default scope is: public
> Api Call does not send scope parameter:
> Expected output: Token with public scope.

And @kapilmittal said:

> return only those default scopes that are allowed by the application.

That is exactly what was said above. Default scope is `public`, application has this scope, and it is returned if no parameters passed. :thinking: 

Anyway, feel free to send a PR, we will take a look at this issue a little bit closer.

**Comment by nbulaj** [comment] 2018-04-20 11:14
@kapilmittal @GeminPatel @rishabhsairawat you can check it now

**Comment by nbulaj** [comment] 2018-04-23 14:52
Thanks to @rishabhsairawat we have another improvements, you can check it in master. Now scopes intersection is done in `BaseRequest` class

**Comment by nbulaj** [comment] 2018-05-11 08:29
Hi @kapilmittal , can you confirm please that the problem is solved?

**Comment by nbulaj** [comment] 2018-05-17 14:33
Closing this stale issue, let me know if problem still exists (check master branch, not stable gem unless it is 5.0)

**Closed by nbulaj** 2018-05-17 14:33 UTC
Labels: bug?
